/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/*
1 pt for weather function and tests
1 pt for tallying function and tests
3 pts for linter application and associated tests to catch all errors
1 pts for README
 */

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

public class App {
    public static String weather(int[][] array) {
        HashSet<Integer> h_set = new HashSet<>();
        StringBuilder final_anser = new StringBuilder();
        for (int[] row : array) {
            for (int el : row) {
                h_set.add(el);
            }
        }
        int min = array[0][0], max = array[0][0];
        for (int[] weeklyMonthTemperature : array) {
            for (int index : weeklyMonthTemperature) {
                if (index >= max) {
                    max = index;
                }
                if (index <= min) {
                    min = index;
                }
            }
        }
        final_anser.append("Highest is ").append(max).append("\n");
        final_anser.append("Lowest is ").append(min).append("\n\n");

        int i = min;
        while (i < max) {
            if (!h_set.contains(i))
                final_anser.append("Never seen ").append(i).append("\n");
            System.out.println();
            i++;
        }
        return final_anser.toString();
    }

    public static String tally(List<String> votes) {

        HashSet<String> datas = new HashSet<>(votes);

        int numVotes = 0;
        String winner = "";

        for (String item : datas) {
            int count = Collections.frequency(votes, item);//most votes
            if (numVotes < count) {
                numVotes = count;
                winner = (item);
            } else if (numVotes == count) {
                winner = "Two gets same votes";
            }
        }
        return winner;
    }

    public static int FileReaderCountErrors(String filePath) throws IOException {
        int count = 0;
        Path path = Paths.get(filePath);
        System.out.println(path.toAbsolutePath());
        String semicolon = ";";
        String semicolon1 = "{";
        String semicolon2 = "}";
        String semicolon3 = "if";
        String semicolon4 = "else";

        Scanner scanner = new Scanner(path);
        int line = 0;

        while (scanner.hasNext()) {
            String this_line = scanner.nextLine();
            line++;
            if (this_line.endsWith(semicolon1) || this_line.endsWith(semicolon2) || this_line.endsWith(semicolon3) || this_line.endsWith(semicolon4))
                continue;
            if (!this_line.endsWith(semicolon)) {

                    System.out.println("Line " + line + ": Missing semicolon.");
                    count++;

            }
        }
        return count;
    }


    public static void main(String[] args) throws IOException {

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };


        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        System.out.println(weather(weeklyMonthTemperatures));
        String winner = tally(votes);
        System.out.println(winner + " received the most votes!");
        System.out.println();

        String path = "C:\\Users\\Ahmad Abdallah\\Desktop\\401\\java-fundamentals\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js";
        FileReaderCountErrors(path);
    }

}


