/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        roll(4);
        System.out.println();
        int[] arr = {1, 2, 7,6, 6};
        System.out.println(containsDuplicates(arr));
        System.out.println(Calculating_Averages(arr));
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        Arrays_Averages(weeklyMonthTemperatures);

    }

    public static int[] roll(int n) {
        System.out.println();
        int[] arr = new int[n];
        for (int i = 0; i < n; i++) {
            int x = (int) (6.0 * Math.random()) + 1;
            arr[i] = x;
        }
        for (int el : arr) {
            System.out.print(el + " ");
        }
        return arr;
    }


    public static boolean containsDuplicates(int[] array) {
        System.out.println();

        boolean result = false;
        for (int k =0;k<= array.length-1;k++) {
            for (int i =0;i<= array.length-1;i++) {
                if(i!=k){
                if (array[k] == array[i])
                    result = true;
            }}
        }
        return result;
    }


    public static double Calculating_Averages(int[] array) {
        System.out.println();

        double result = 0;
        for (int j : array)
            result += j;
        result /= array.length;

        return result;

    }

    public static int[] Arrays_Averages(int[][] array) {
        double count = 0;
        int index = 0;
        double[] average = new double[array.length];
        double low;


        for (int row = 0; row < array.length; row++) {

            for (int col = 0; col < array[row].length; col++) {
                count += array[row][col];
            }
            average[row] = count / array[row].length;
            count = 0;
        }
        low = average[0];

        for (int ind = 1; ind < average.length; ind++) {
            if (average[ind] < low) {
                low = average[ind];
                index = ind;
            }
        }
        System.out.println();
        System.out.println("lowest array average is array =>" + index);
        System.out.println();

        for (int i = 0; i < array[index].length; i++) {
            System.out.print(array[index][i] + " ");
        }
        return array[index];
    }


}