/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    String inputFilePath = "C:\\Users\\Ahmad Abdallah\\Desktop\\401\\java-fundamentals\\java-fundamentals\\bitmap-transformer\\app\\src\\main\\resources\\original.bmp";
    String outputFilePath = "C:\\Users\\Ahmad Abdallah\\Desktop\\401\\java-fundamentals\\java-fundamentals\\bitmap-transformer\\app\\src\\main\\resources\\";
    String grayFile = "test.bmp";
    Bitmap testFile = new Bitmap(inputFilePath, outputFilePath, grayFile);
    @Test
    public void testReadFile() {
        assertEquals(testFile.read_File(),true,"File not found");
    }
    @Test
    public void testSaveFile() {
        testFile.read_File();
        assertEquals(testFile.save_File(),true,"File not saved");
    }
    @Test
    public void testGray() {
        testFile.read_File();
        assertEquals(testFile.Gray_Scale(),true);
    }
    @Test
    public void testImageFlipHorizontal() {
        testFile.read_File();
        int lastRGBVal = -16180729;
        assertEquals(testFile.imageFlipHorizontal(),lastRGBVal,"File not flipped horizontally");
    }
    @Test
    public void testnegativeImage() {
        testFile.read_File();
        assertEquals(testFile.negativeImage(),true,"\"File not swap to negativeImage\"");
    }
}