/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.IOException;
import org.junit.jupiter.api.Test;
import static linter.App.FileReaderCountErrors;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void OneError() throws IOException {
        String path ="C:\\Users\\Ahmad Abdallah\\Desktop\\401\\java-fundamentals\\java-fundamentals\\linter\\app\\src\\test\\resources\\one.js";
        int Result = FileReaderCountErrors(path);
        assertEquals(1, Result);
    }

    @Test
    void FewError() throws IOException {
        String path ="C:\\Users\\Ahmad Abdallah\\Desktop\\401\\java-fundamentals\\java-fundamentals\\linter\\app\\src\\test\\resources\\few.js";
        int Result = FileReaderCountErrors(path);
        assertTrue(Result <= 5);
    }

    @Test
    void Empty() throws IOException {
        String path ="C:\\Users\\Ahmad Abdallah\\Desktop\\401\\java-fundamentals\\java-fundamentals\\linter\\app\\src\\test\\resources\\empty.js";
        int Result = FileReaderCountErrors(path);
        Boolean flag = false;
        if (Result == 0) {
            flag = true;
        }
        assertEquals(true, flag);
    }

    @Test
    void NoError() throws IOException {
        String path ="C:\\Users\\Ahmad Abdallah\\Desktop\\401\\java-fundamentals\\java-fundamentals\\linter\\app\\src\\test\\resources\\no_errors.js";
        int Result = FileReaderCountErrors(path);
        assertEquals(0, Result);
    }

    @Test
    void ManyError() throws IOException {
        String path ="C:\\Users\\Ahmad Abdallah\\Desktop\\401\\java-fundamentals\\java-fundamentals\\linter\\app\\src\\test\\resources\\many.js";
        int Result = FileReaderCountErrors(path);
        assertTrue(Result <= 10);
    }
}







